# Generated by Django 3.2.9 on 2021-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20211112_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='test', help_text='Максимум 250 символів', max_length=250, verbose_name='Категорія'),
        ),
    ]
