# Generated by Django 3.2.9 on 2021-11-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Максимум 250 символів', max_length=250, verbose_name='Категорія'),
        ),
    ]
